name: auto-build
run-name: ${{ github.actor }} running...
on:
  pull_request:
    branches:
      - develop
jobs:
  check-build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Cargo check
        run: cargo check --verbose
      - name: Build wasm-pack
        run: wasm-pack build --target web --verbose
